- R/createMakefiles.R
- inst/doc/vizlabExample.Rmd
- inst/doc/vizlabExample.html
- inst/testviz/viz.yaml
- vignettes/vizlabExample.Rmd
@wdwatkins - review? Addressing #82. The functional changes are all in R/createMakefiles.R: I'm creating a warning that appears in the shell when calling `make` if any viz.yaml items have a `scripts:` dependency that's a directory rather than a file. All the changes in other files are documentation for that one functional change.
I'm about to submit a parallel PR for USGS-VIZLAB/example - would be great if you could review these together.
See recent comments in #82, plus the new output in the vignette, for examples of how this works.
> encourage non-directory script dependencies

- R/createMakefiles.R
@jiwalker-usgs - review? i think this should fix the issue we just identified with `callFunction.R` not always getting copied over.
> should fix #115

- R/publishLandingPage.R
@jiwalker-usgs thumbnails are still broken, I think this fixes it. It should be relative to vizlab, so it needs the correct viz before the thumbnail path. Can't really test locally though, so hopefully I can see this on dev after I merge and it's deployed.
> thumbnails will work now??

- inst/doc/vizlabExample.R
- inst/doc/vizlabExample.Rmd
- inst/doc/vizlabExample.html
- vignettes/vizlabExample.Rmd
Typo pointed out by a potential user - thanks, Jonathan!
> fix typo in vignette (install.github -> install_github)

- R/createMakefiles.R
* switch order of " and ' for non-x64 Rscript.exe
* send Rscript output to file rather than build window
* move config.rdses from cache/config to vizlab/make/config, idea #193 (5)
> refinements for #193

- R/createMakefiles.R
it's still a fragile function, but this change helps with a new bug (my bad, from last sprint) in creating makefiles when one or more items have a directory as a `scripts:` dependency. the error in example/vizlab/make/log/make/fetch.Rout was this:
```
> # Call function
> message("Running function")
Running function
> do.call(cmd.args$fun, if(is.null(cmd.args$funargs)) list() else cmd.args$funargs)
Error in file(filename, "r") : cannot open the connection
Calls: do.call ... unlist -> lapply -> FUN -> deparse -> parse -> file
In addition: Warning message:
In file(filename, "r") :
cannot open file 'scripts/fetch': Permission denied
Execution halted
```
but with this PR the function now only tries to parse files, not directories - works much better.
> reduce fragility of needsTimestamp()

- R/publish.R
- inst/landing/viz.yaml
Added the vizlab favicon to the landing page publisher and to the landing page viz.yaml.  The favicon is in the vizlab resources yaml, so was pretty easy to call out to.
> #253 favicon for landing page

- R/validateVizYaml.R
Added a check to `validateVizYaml()`, which has been a placeholder function for a long time. `validateVizYaml()` doesn't automatically get called yet, but I have plans for that. And maybe eventually we'll add other checks as well. This PR introduces checks for (1) missing viz IDs, (2) viz IDs that can't be parsed by R at all, and (3) viz IDs that get parsed to more than one R object (e.g., "plot-cars" gets parsed to c("plot", "-", "cars"), which is no good if we're going to use IDs as R variable names).
Applied to the current USGS-VIZLAB/example repo, this will produce the same type of error for every id because they're all currently dash-separated:
```
viz item id parses to >1 R variable name: plot-info
```
> Validate viz yaml

- R/createRemakefile.R
First cut at createRemakefile() function.
* After running `createRemakefile()` in USGS-VIZLAB/example, it's [mostly] possible to run `remake::make(remake_file='remake.yaml')` and build the entire example project! That makes for a good start on #246.
* The [mostly] caveat from the previous bullet is that when I run `remake::make(remake_file='remake.yaml')` in a fresh session, things break unless I manually source those files listed in `sources:`. Why would this be? I don't understand.
* Creates a single remake.yaml for all of the blocks, and looks for cross references in any phase (not just the current one), so also addresses #88 (but testing would be nice)
* Includes recipes for those resources that are depended on by other targets, so also addresses #215 (but are these resources now …
> first cut at createRemakefile

- inst/js/tooltip.js
This is an add-on to #282 , but makes the tooltip box as a single <path> instead of a <rect> (for the box) and a <path> for the triangle tip. 
This gets rid of the little bit of separation or overlap between the triangle and the box that appears in other vizzies:
> Tooltip path

- inst/landing/css/owi.css
- inst/landing/templates/owiNav.mustache
- inst/landing/viz.yaml
Currently just deleted the logo instead of replacing with anything - can wait on the I2D2 logo. I left the banner because the menu button is still there. Closes #255
> Remove OWI logo from vizlab landing page

- DESCRIPTION
- inst/mimetypes.default.yaml
Related to the issue described in https://github.com/USGS-VIZLAB/how-to-gdp/pull/28 where gifs would make it to target, but would not end up being used in `index.html`.
> add gif as img mimetype

- DESCRIPTION
- R/export.R
- R/publish.R
- R/util.R
- inst/mimetypes.default.yaml
- inst/viz.defaults.yaml
This PR primarily resolves #263, which requests a publish.json method. I also added a publish.tabular method because both are needs for using d3 (or jquery) for more complex javascript-side data viz, and because the two methods are identical. 
The final paragraph in the description of issue #263 suggests that publish.json should include a call to `export`; this is accomplished by the call to `NextMethod`, which will resolve to `publish.resource`, which calls `export` and also (importantly!) copies the file into `target/data`.
Partly to make the file copying happen, and partly because I can't think of cases where file copying *shouldn't* happen, I've made the default in `export.resource` be for doExport to be TRUE. This allowed me to simplify the use and implementation of `doExport` …
> publish.json, publish.tabular, and simpler export, buildContext, and expandDependencies

- tests/testthat/tests-timestamps.R
try to fix the sciencebase errors from #327, which I think occur because sciencebase stopped allowing single-user accounts to have public items. the new remoteItemId points to https://www.sciencebase.gov/catalog/item/5a8309a7e4b00f54eb32959f in the new USGS-R Sandbox community (ScienceBase Catalog -> USGS-R Sandbox -> usgs-r-pkgs-tests -> vizlab), which is public.
probably won't fix all of #327, but i hope it's a start.
> point CuyahogaTDS.csv to new public item

- inst/css/socialMedia.css
FireFox doesn't like SVG's to have width 100%, hence the social media Icons not showing up in their browser.  Width 25px should work on all browsers and we can just not have this issue next Viz and fix the current problem.
> Social Media icon fix for all browsers

- R/publish.R
- R/publishLandingPage.R
- tests/testthat/tests-publish.R
- tests/testthat/tests-publishLandingPage.R
- tests/testthat/tests-timestamps.R
should resolve, or help with, issue #327 and current test failures in #354. these issues include 
from #327:
```
1. Failure: alwaysCurrent doesn't get rebuilt unless missing (@tests-timestamps.R#15) 
`messages` does not match "[ BUILD ] data/mayfly_nymph.csv".
Actual values:
* [ \033[33m LOAD\033[39m ] \n
* (       ) vizlab/remake/timestamps/cuyahoga.txt\n
* (       ) vizlab/remake/timestamps/never_current.txt\n
* Starting build at 2018-01-10 10:00:39\n
* [ \033[33m READ\033[39m ]                                                |  \033[90m# loading sources\033[39m\n
* < \033[36m MAKE\033[39m > mayfly_nymph\n
* [ \033[34mBUILD\033[39m ] arguments_all                                  |  \033[90marguments_all <-...\033[39m\n
* [ \033[33m READ\033[39m ] …
```
> address testthat problems: redo from my how-to-gdp branch

- inst/css/header.css
- inst/templates/footer.mustache
Still noticed some tiny details in how-to-gdp that would be useful for future vizzies. 
On mobile, the header words wrapped and disappeared:
This fixes that:
Desktop remains the same:
Also in the footer, the title "Related Visualizations" looked and acted like a link but didn't link to anything, so changed the template. Same for the title of the related vizzie, but I added the URL to that since it should link.
No noticeable appearance, but underlines on hover only work for the ones with links now.
> css update title wrap + links in footer

- inst/css/content.css
So changed svg-container to main svg as it has the code for the big fancy interactive SVG.  The secondary was needed to avoid them inheriting the main-svg width CSS on Desktop. 
I think this works for now, but maybe some more thought needs to go into this for fixing IE and having the ability to do as many fancy SVG's as we want as easily as we can.
> New secondary and main svg

- DESCRIPTION
- inst/templates/fullPage.mustache
Fixes #374. Working on being smarter about where and when things are loaded. Moving the `usgs-analytics.js` after everything else on the page.
For water-use-15, it still doesn't load after the actual map data, but does load after all of the footer images (https://github.com/USGS-VIZLAB/water-use-15/issues/313 will work on lazy loading to let javascript stuff happen first).
Before
After
> load usgs-analytics after the footer

- DESCRIPTION
- inst/css/footer.css
adding `background:#414042;` to `footer a{}` css element to satisfy 508 contrast error about text links in footer (regular-view contrast looks fine, but contrast would fail if a browser displayed the page without some visual elements)
This change is required to fully resolve 508 errors as in https://github.com/USGS-VIZLAB/water-use-15/pull/351
> Footer contrast

- R/publish.R
- R/publishLandingPage.R
Edited how publish-date is used so that blank fields never get built, dev builds anything with a date past or future, and prod only builds dates that are today's date or in the past.
Fix for Harvey and Irma: We aren't sure why this was implemented, but commented it out for now. It does not break any tests when we do. https://github.com/USGS-VIZLAB/vizlab/commit/ef628bace5231525024026f63c3a5529cd5a879f
That is was was preventing Harvey and Irma from building because they get that warning due to https://github.com/USGS-VIZLAB/hurricane-harvey/blob/master/viz.yaml#L434 and https://github.com/USGS-VIZLAB/hurricane-irma/blob/master/viz.yaml#L696
> Fixes what is on dev & brings Harvey/Irma back

- DESCRIPTION
- R/vizmake.R
- R/webpacker.R
Tested this with `gage-conditions`. The dev bundle.js was 1.2 MB and the beta bundle.js was 250 KB.
```
vizlab::vizmake(webpack_build_cfg = "dev") # uses webpack --mode development
vizlab::vizmake(webpack_build_cfg = "beta") # uses webpack --mode production
```
> kick off different webpack build configs for dev vs prod

- DESCRIPTION
- inst/css/content.css
Thanks to some quick screensharing with @mwernimont, we figured out why the header and footer spacing looked strange in `gage-conditions` (see https://github.com/USGS-VIZLAB/gage-conditions/issues/20). We updated `content.css` with the necessary style specs and increased the version.
> content.css addition
