DESCRIPTION
needed min version of `sbtools` to run make for `climate-fish-habitat` viz
:+1:
=> min version

R/fetch.R, inst/testviz/viz.yaml, tests/testthat.R, tests/testthat/tests-vizlab.R
Hopefully we can find some bugs and get the coverage up!
=> Adding in testing harness

inst/templates/keynote.mustache, inst/templates/list.mustache, tests/testthat/tests-vizlab.R
There is currently a single test file, I'd like to split this out going forward.
Also, whether or not to do `{{{ }}}` vs `{{ }}` should be discussed, I'm hesitant to always allow triple-mustache, but special characters may make their way in sometimes.
=> Template lib

tests/testthat/tests-publishLandingPage.R
This broke with path fix on climate fish, fix may collide with unmerged branch
=> Fix test for corrected path

inst/templates/footer.mustache
=> footer templates changes

inst/templates/fullPage.mustache
=> adding noscript

DESCRIPTION, inst/doc/vizlabExample.R, inst/doc/vizlabExample.Rmd, inst/doc/vizlabExample.html, vignettes/vizlabExample.Rmd
#42 .Rmarkdown is actually accessible as vignette.  Still needs updating
=> vignette setup

R/publishLandingPage.R, tests/testthat/tests-vizlab.R
still need to run `publishLandingPage()` when all the viz.yamls get updated to check that this works
=> use thumbnail-landing for landing page

inst/landing/css/landing.css, inst/landing/css/owi.css, inst/landing/templates/owiNav.mustache
@jiwalker-usgs OWI new nav and data science page is live so just making the two navs match
=> adding data science and vizlab to nav

inst/footer/css/footer.css, inst/footer/css/footer.less, inst/footer/js/templates/footer.mustache, inst/templates/footer.mustache
@jiwalker-usgs Took the template from water use and put it in the inst footer template, and then switched the vizlab footer CSS for the water use footer CSS.
=> vizlab to match water use footer

R/publish.R, R/publishLandingPage.R
per @ldecicco-USGS we want the freshest viz to be on top
=> reverse sorting landing page

inst/css/footer.css, inst/resource.library.yaml, inst/templates/footer.mustache, inst/templates/fullPage.mustache, inst/templates/header.mustache
=> Footer Tweaks and Header template

inst/css/footer.css
=> footer h4 font weight

R/publish.R
template changes caused some issues with the header and footer
=> fixes to header and footer

DESCRIPTION, R/publish.R, R/readData.R, R/render.R, man/readData.Rd, tests/testthat/tests-publish.R
* leftover classes for images
* switch to readr for text
* improved partials
=> A few changes for internal-analytics

R/profile.yaml.R
here you go, @lindsaycarr - could you try out the new `createProfile`?
=> add backslashes to default windows profile.yaml; fixes #181

DESCRIPTION, R/publish.R
=> embed feature has correct relative file path 

DESCRIPTION
Using hadley's 9000 to indicate in development
=> Starting out a 0.2.x branch for sprint

inst/css/socialMedia.css, inst/resource.library.yaml, inst/templates/verticalSocialMedia.mustache
Made a vertical template for the social media options.
=> links and vertical template

DESCRIPTION, R/createMakefiles.R, R/fetchTimestamp.R, tests/testthat/tests-vizlab.R
* updateConfigInfoFile now updates when values change (issue from slack/maria: need _any_ change to `mobile-metadata` to cause rebuild of `view-limits-mobile`)
* SB dateUploadeds are UTC - hopefully will fix travis build?
=> viz.yaml chunk dependency + sciencebase timezone fix

DESCRIPTION, R/publish.R
Noticed normal svgs were breaking on mobile
=> inject should default to both, need to separate them to differentiate

inst/templates/footer.mustache
=> Fixes #256

inst/resource.library.yaml, inst/templates/header.mustache
Adding full U.S. Geological Survey to logo alt/title text, and making it a link to the USGS page
=> Thought I had this morning

DESCRIPTION
No code changes in this PR, but all but one non-code detail of our october sprint is complete, so incrementing the vizlab version to 0.3.0.
=> declare version 0.3.0

.travis.yml, DESCRIPTION
this PR is also in support of https://github.com/USGS-VIZLAB/water-use-15/pull/79#issuecomment-373129131
=> ask travis to be more patient

inst/css/footer.css, inst/templates/footer.mustache
So making these changes for the gdp-how viz, looks to be fixing the water-use footer issues as well.
=> footer changes

inst/css/footer.css
Related Items text was being pushed down, this fixed it.
=> related item a help

inst/css/content.css, inst/templates/printall.mustache
Added the class .viz-text to always have some base text CSS.
=> Text has no margin

DESCRIPTION, man/authRemote.Rd, man/createBlockMakefile.Rd, man/createMakeBlockRules.Rd, man/export.Rd, man/fetch.Rd, man/fetchTimestamp.Rd, man/fetchTimestampHelpers.Rd, man/fetchTimestampMethods.Rd, man/getContentInfo.Rd, man/initializeVizRepo.Rd, man/process.Rd, man/publish.Rd, man/readData.Rd, man/vizmake.Rd, man/webpacker.Rd, vignettes/docker.Rmd
This is mostly the material from the water-use-15 readme, I reworded just added the contents of the docker-relevant files and reworded a few things.
I had thought I remembered there being comments in a google doc somewhere about changes to make, but I didn't see those anywhere.
=> Docker vignette
